version: '3.8'

services:
  # Сервис PostgreSQL
  postgres:
    image: postgres:13
    container_name: filmoteca-postgres
    environment:
      POSTGRES_DB: filmoteca-db
      POSTGRES_USER: bender
      POSTGRES_PASSWORD: zirael228
    ports:
      - "5432:5432"
    networks:
      - filmoteca-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-db.sql

  # Сервис Spring Boot (бэкенд)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filmoteca-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://filmoteca-postgres:5432/filmoteca-db
      SPRING_DATASOURCE_USERNAME: bender
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update # или validate для production
    depends_on:
      - postgres
    networks:
      - filmoteca-network

  # Сервис React (фронтенд)
  frontend:
    build:
      context: C:/frontend/filmoteca
      dockerfile: Dockerfile
    container_name: filmoteca-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - filmoteca-network

# Объявляем тома и сети
networks:
  filmoteca-network:
    driver: bridge

volumes:
  postgres-data: